// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Environmental_Monitoring
{
    public partial class ResignModel
    {
        /// <summary>
        /// model input class for ResignModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"ContractType")]
            public string ContractType { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"WasOnTime")]
            public string WasOnTime { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"PollutionCount")]
            public float PollutionCount { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"WarningCount")]
            public float WarningCount { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"TotalContracts")]
            public float TotalContracts { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Label")]
            public bool Label { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"CorrectionCount")]
            public float CorrectionCount { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"DaysOverdue")]
            public float DaysOverdue { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ResignModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ContractType")]
            public float[] ContractType { get; set; }

            [ColumnName(@"WasOnTime")]
            public float[] WasOnTime { get; set; }

            [ColumnName(@"PollutionCount")]
            public float PollutionCount { get; set; }

            [ColumnName(@"WarningCount")]
            public float WarningCount { get; set; }

            [ColumnName(@"TotalContracts")]
            public float TotalContracts { get; set; }

            [ColumnName(@"Label")]
            public bool Label { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ResignModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
