//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Environmental_Monitoring {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Environmental_Monitoring.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Thông số mới.
        /// </summary>
        internal static string AddEditParam_AddTitle {
            get {
                return ResourceManager.GetString("AddEditParam_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa Thông số.
        /// </summary>
        internal static string AddEditParam_EditTitle {
            get {
                return ResourceManager.GetString("AddEditParam_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thông số và phòng ban phụ trách không được để trống..
        /// </summary>
        internal static string AddEditParam_ValidationWarning {
            get {
                return ResourceManager.GetString("AddEditParam_ValidationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự Đoán.
        /// </summary>
        internal static string AI_Button_Predict {
            get {
                return ResourceManager.GetString("AI_Button_Predict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức Độ Ô Nhiễm.
        /// </summary>
        internal static string AI_Label_PollutionLevel {
            get {
                return ResourceManager.GetString("AI_Label_PollutionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ô Nhiễm.
        /// </summary>
        internal static string AI_Panel_Pollution {
            get {
                return ResourceManager.GetString("AI_Panel_Pollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tái Ký.
        /// </summary>
        internal static string AI_Panel_Resign {
            get {
                return ResourceManager.GetString("AI_Panel_Resign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Tên Khách Hàng.
        /// </summary>
        internal static string AI_Placeholder_Customer {
            get {
                return ResourceManager.GetString("AI_Placeholder_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Dự Đoán.
        /// </summary>
        internal static string AI_Title {
            get {
                return ResourceManager.GetString("AI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật thông tin nhân viên thành công..
        /// </summary>
        internal static string Alert_AddEmployee_Edit {
            get {
                return ResourceManager.GetString("Alert_AddEmployee_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm nhân viên mới thành công..
        /// </summary>
        internal static string Alert_AddEmployee_Success {
            get {
                return ResourceManager.GetString("Alert_AddEmployee_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn XÓA nhân viên có Mã: {0}?.
        /// </summary>
        internal static string Alert_DeleteConfirm_Message {
            get {
                return ResourceManager.GetString("Alert_DeleteConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận xóa.
        /// </summary>
        internal static string Alert_DeleteConfirm_Title {
            get {
                return ResourceManager.GetString("Alert_DeleteConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa! Dữ liệu này đang được sử dụng ở bảng khác..
        /// </summary>
        internal static string Alert_DeleteError_InUse {
            get {
                return ResourceManager.GetString("Alert_DeleteError_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa. {0}.
        /// </summary>
        internal static string Alert_DeleteError_InUse_Specific {
            get {
                return ResourceManager.GetString("Alert_DeleteError_InUse_Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên thành công..
        /// </summary>
        internal static string Alert_DeleteSuccess {
            get {
                return ResourceManager.GetString("Alert_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Chi Tiết.
        /// </summary>
        internal static string Alert_ErrorDetails {
            get {
                return ResourceManager.GetString("Alert_ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string Alert_ErrorTitle {
            get {
                return ResourceManager.GetString("Alert_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối CSDL.
        /// </summary>
        internal static string Alert_Forgot_DbError {
            get {
                return ResourceManager.GetString("Alert_Forgot_DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc Số điện thoại không chính xác. Vui lòng thử lại..
        /// </summary>
        internal static string Alert_Forgot_InvalidCredentials {
            get {
                return ResourceManager.GetString("Alert_Forgot_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã OTP..
        /// </summary>
        internal static string Alert_Forgot_OTPEmpty {
            get {
                return ResourceManager.GetString("Alert_Forgot_OTPEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã hết hạn..
        /// </summary>
        internal static string Alert_Forgot_OTPExpired {
            get {
                return ResourceManager.GetString("Alert_Forgot_OTPExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không chính xác..
        /// </summary>
        internal static string Alert_Forgot_OTPMismatch {
            get {
                return ResourceManager.GetString("Alert_Forgot_OTPMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực OTP thành công!.
        /// </summary>
        internal static string Alert_Forgot_OTPValid {
            get {
                return ResourceManager.GetString("Alert_Forgot_OTPValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới phải có ít nhất 6 ký tự..
        /// </summary>
        internal static string Alert_Forgot_PasswordLength {
            get {
                return ResourceManager.GetString("Alert_Forgot_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới và mật khẩu xác nhận không khớp..
        /// </summary>
        internal static string Alert_Forgot_PasswordMismatch {
            get {
                return ResourceManager.GetString("Alert_Forgot_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại..
        /// </summary>
        internal static string Alert_Forgot_PhoneEmpty {
            get {
                return ResourceManager.GetString("Alert_Forgot_PhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không tồn tại..
        /// </summary>
        internal static string Alert_Forgot_PhoneNotFound {
            get {
                return ResourceManager.GetString("Alert_Forgot_PhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi SMS thất bại, vui lòng thử lại..
        /// </summary>
        internal static string Alert_Forgot_SendFail {
            get {
                return ResourceManager.GetString("Alert_Forgot_SendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi mã OTP đến SĐT của bạn!.
        /// </summary>
        internal static string Alert_Forgot_SendSuccess {
            get {
                return ResourceManager.GetString("Alert_Forgot_SendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công! Bạn có thể đăng nhập bằng mật khẩu mới..
        /// </summary>
        internal static string Alert_Forgot_Success {
            get {
                return ResourceManager.GetString("Alert_Forgot_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Email và Số điện thoại để xác minh..
        /// </summary>
        internal static string Alert_Forgot_ValidationEmpty {
            get {
                return ResourceManager.GetString("Alert_Forgot_ValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi khi tải dữ liệu:.
        /// </summary>
        internal static string Alert_LoadDataError {
            get {
                return ResourceManager.GetString("Alert_LoadDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải tài nguyên ngôn ngữ:.
        /// </summary>
        internal static string Alert_LoadLanguageError {
            get {
                return ResourceManager.GetString("Alert_LoadLanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối dữ liệu hệ thống.
        /// </summary>
        internal static string Alert_Login_DbError {
            get {
                return ResourceManager.GetString("Alert_Login_DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác. Vui lòng thử lại..
        /// </summary>
        internal static string Alert_Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Alert_Login_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công!.
        /// </summary>
        internal static string Alert_Login_Success {
            get {
                return ResourceManager.GetString("Alert_Login_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đầy đủ tài khoản và mật khẩu.
        /// </summary>
        internal static string Alert_Login_ValidationEmpty {
            get {
                return ResourceManager.GetString("Alert_Login_ValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Khi Lưu Cài Đặt:.
        /// </summary>
        internal static string Alert_SaveError {
            get {
                return ResourceManager.GetString("Alert_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Lưu Cài Đặt Thành Công!.
        /// </summary>
        internal static string Alert_SaveSuccess {
            get {
                return ResourceManager.GetString("Alert_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        internal static string Alert_SuccessTitle {
            get {
                return ResourceManager.GetString("Alert_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        internal static string Alert_WarningTitle {
            get {
                return ResourceManager.GetString("Alert_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm sinh.
        /// </summary>
        internal static string BirthYear {
            get {
                return ResourceManager.GetString("BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ Doanh Nghiệp.
        /// </summary>
        internal static string Business_Address_Placeholder {
            get {
                return ResourceManager.GetString("Business_Address_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Đồng.
        /// </summary>
        internal static string Business_Contract {
            get {
                return ResourceManager.GetString("Business_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Hợp Đồng.
        /// </summary>
        internal static string Business_ContractID_Placeholder {
            get {
                return ResourceManager.GetString("Business_ContractID_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách Hàng.
        /// </summary>
        internal static string Business_Customer {
            get {
                return ResourceManager.GetString("Business_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Doanh Nghiệp.
        /// </summary>
        internal static string Business_CustomerName_Placeholder {
            get {
                return ResourceManager.GetString("Business_CustomerName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký Hiệu Doanh Nghiệp.
        /// </summary>
        internal static string Business_CustomerSymbol_Placeholder {
            get {
                return ResourceManager.GetString("Business_CustomerSymbol_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Dự Kiến Trả Kết Quả.
        /// </summary>
        internal static string Business_DueDate_Placeholder {
            get {
                return ResourceManager.GetString("Business_DueDate_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Business_EmailCustomer_Placeholder {
            get {
                return ResourceManager.GetString("Business_EmailCustomer_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Viên Thụ Lý.
        /// </summary>
        internal static string Business_Employee {
            get {
                return ResourceManager.GetString("Business_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Viên Thụ Lý.
        /// </summary>
        internal static string Business_Employee_Placeholder {
            get {
                return ResourceManager.GetString("Business_Employee_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người Đại Diện.
        /// </summary>
        internal static string Business_Representative_Placeholder {
            get {
                return ResourceManager.GetString("Business_Representative_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Khách Hàng Và Hợp Đồng.
        /// </summary>
        internal static string Business_Title {
            get {
                return ResourceManager.GetString("Business_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng Ý.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh Doanh.
        /// </summary>
        internal static string Contract_Tab_Business {
            get {
                return ResourceManager.GetString("Contract_Tab_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng Thí Nghiệm.
        /// </summary>
        internal static string Contract_Tab_Lab {
            get {
                return ResourceManager.GetString("Contract_Tab_Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý.
        /// </summary>
        internal static string Contract_Tab_Manager {
            get {
                return ResourceManager.GetString("Contract_Tab_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế Hoạch.
        /// </summary>
        internal static string Contract_Tab_Plan {
            get {
                return ResourceManager.GetString("Contract_Tab_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết Quả.
        /// </summary>
        internal static string Contract_Tab_Result {
            get {
                return ResourceManager.GetString("Contract_Tab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện Trường.
        /// </summary>
        internal static string Contract_Tab_Scene {
            get {
                return ResourceManager.GetString("Contract_Tab_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Hợp Đồng.
        /// </summary>
        internal static string Contract_Title {
            get {
                return ResourceManager.GetString("Contract_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Tiết Hợp đồng: {0}.
        /// </summary>
        internal static string ContractDetail_Title {
            get {
                return ResourceManager.GetString("ContractDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý.
        /// </summary>
        internal static string ContractType_Quarterly {
            get {
                return ResourceManager.GetString("ContractType_Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Tháng.
        /// </summary>
        internal static string ContractType_Semiannual {
            get {
                return ResourceManager.GetString("ContractType_Semiannual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện Trường.
        /// </summary>
        internal static string Dept_Field {
            get {
                return ResourceManager.GetString("Dept_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí Nghiệm.
        /// </summary>
        internal static string Dept_Lab {
            get {
                return ResourceManager.GetString("Dept_Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên.
        /// </summary>
        internal static string Employee_AddButton {
            get {
                return ResourceManager.GetString("Employee_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhân viên.
        /// </summary>
        internal static string Employee_Title {
            get {
                return ResourceManager.GetString("Employee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        internal static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng điền đầy đủ tất cả thông tin..
        /// </summary>
        internal static string Error_AllFieldsRequired {
            get {
                return ResourceManager.GetString("Error_AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hợp đồng phải bắt đầu bằng &apos;HD-&apos;..
        /// </summary>
        internal static string Error_ContractIDPrefix {
            get {
                return ResourceManager.GetString("Error_ContractIDPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xác định khách hàng..
        /// </summary>
        internal static string Error_CustomerUndefined {
            get {
                return ResourceManager.GetString("Error_CustomerUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi.
        /// </summary>
        internal static string Error_General {
            get {
                return ResourceManager.GetString("Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tạo file PDF.
        /// </summary>
        internal static string Error_GeneratePDF {
            get {
                return ResourceManager.GetString("Error_GeneratePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng email không hợp lệ..
        /// </summary>
        internal static string Error_InvalidEmailFormat {
            get {
                return ResourceManager.GetString("Error_InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị nhập không hợp lệ.
        /// </summary>
        internal static string Error_InvalidValue {
            get {
                return ResourceManager.GetString("Error_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải danh sách hợp đồng.
        /// </summary>
        internal static string Error_LoadContracts {
            get {
                return ResourceManager.GetString("Error_LoadContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải danh sách nhân viên.
        /// </summary>
        internal static string Error_LoadEmployees {
            get {
                return ResourceManager.GetString("Error_LoadEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải dữ liệu thử nghiệm.
        /// </summary>
        internal static string Error_LoadExperimentData {
            get {
                return ResourceManager.GetString("Error_LoadExperimentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải thông số của mẫu.
        /// </summary>
        internal static string Error_LoadParameters {
            get {
                return ResourceManager.GetString("Error_LoadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải thông tin thông số.
        /// </summary>
        internal static string Error_LoadParamInfo {
            get {
                return ResourceManager.GetString("Error_LoadParamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải mẫu môi trường.
        /// </summary>
        internal static string Error_LoadSampleTemplates {
            get {
                return ResourceManager.GetString("Error_LoadSampleTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải lại thông số.
        /// </summary>
        internal static string Error_ReloadParameters {
            get {
                return ResourceManager.GetString("Error_ReloadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy mẫu (SampleID) để lưu giá trị..
        /// </summary>
        internal static string Error_SampleIDNotFound {
            get {
                return ResourceManager.GetString("Error_SampleIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi lưu dữ liệu.
        /// </summary>
        internal static string Error_SaveData {
            get {
                return ResourceManager.GetString("Error_SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi lưu thông số mới.
        /// </summary>
        internal static string Error_SaveNewParam {
            get {
                return ResourceManager.GetString("Error_SaveNewParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi lưu kế hoạch.
        /// </summary>
        internal static string Error_SavePlan {
            get {
                return ResourceManager.GetString("Error_SavePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi lưu giá trị.
        /// </summary>
        internal static string Error_SavingValue {
            get {
                return ResourceManager.GetString("Error_SavingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi chọn hợp đồng.
        /// </summary>
        internal static string Error_SelectContract {
            get {
                return ResourceManager.GetString("Error_SelectContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi cập nhật thông số.
        /// </summary>
        internal static string Error_UpdateParam {
            get {
                return ResourceManager.GetString("Error_UpdateParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu để lưu..
        /// </summary>
        internal static string Exp_NoDataToSave {
            get {
                return ResourceManager.GetString("Exp_NoDataToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu {0} trạng thái ô nhiễm và chuyển sang Phòng Kết Quả..
        /// </summary>
        internal static string Exp_SaveSuccess {
            get {
                return ResourceManager.GetString("Exp_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác Thực Tài Khoản.
        /// </summary>
        internal static string Forgot_Account_Verification {
            get {
                return ResourceManager.GetString("Forgot_Account_Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác Nhận.
        /// </summary>
        internal static string Forgot_Button_Confirm {
            get {
                return ResourceManager.GetString("Forgot_Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi Mã.
        /// </summary>
        internal static string Forgot_Button_SendCode {
            get {
                return ResourceManager.GetString("Forgot_Button_SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác Thực Mã.
        /// </summary>
        internal static string Forgot_Button_VerifyCode {
            get {
                return ResourceManager.GetString("Forgot_Button_VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác Nhận Mật Khẩu Mới.
        /// </summary>
        internal static string Forgot_Placeholder_ConfirmPass {
            get {
                return ResourceManager.GetString("Forgot_Placeholder_ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Email (Tài khoản).
        /// </summary>
        internal static string Forgot_Placeholder_Email {
            get {
                return ResourceManager.GetString("Forgot_Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Mật Khẩu Mới.
        /// </summary>
        internal static string Forgot_Placeholder_NewPass {
            get {
                return ResourceManager.GetString("Forgot_Placeholder_NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã OTP.
        /// </summary>
        internal static string Forgot_Placeholder_OTP {
            get {
                return ResourceManager.GetString("Forgot_Placeholder_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Số Điện Thoại.
        /// </summary>
        internal static string Forgot_Placeholder_Phone {
            get {
                return ResourceManager.GetString("Forgot_Placeholder_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi Mật Khẩu.
        /// </summary>
        internal static string Forgot_Section_ChangePass {
            get {
                return ResourceManager.GetString("Forgot_Section_ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác Thực Tài Khoản.
        /// </summary>
        internal static string Forgot_Section_Verify {
            get {
                return ResourceManager.GetString("Forgot_Section_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt Mật Khẩu Mới.
        /// </summary>
        internal static string Forgot_Set_New_Password {
            get {
                return ResourceManager.GetString("Forgot_Set_New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên Mật Khẩu.
        /// </summary>
        internal static string Forgot_Title {
            get {
                return ResourceManager.GetString("Forgot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Nhân Viên.
        /// </summary>
        internal static string Form_AddEmployee_Title {
            get {
                return ResourceManager.GetString("Form_AddEmployee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật Nhân Viên.
        /// </summary>
        internal static string Form_UpdateEmployee_Title {
            get {
                return ResourceManager.GetString("Form_UpdateEmployee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ Tên.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng Thái Duyệt.
        /// </summary>
        internal static string Grid_ApprovalStatus {
            get {
                return ResourceManager.GetString("Grid_ApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Duyệt.
        /// </summary>
        internal static string Grid_Approved {
            get {
                return ResourceManager.GetString("Grid_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Đơn.
        /// </summary>
        internal static string Grid_ContractCode {
            get {
                return ResourceManager.GetString("Grid_ContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Hợp Đồng.
        /// </summary>
        internal static string Grid_ContractID {
            get {
                return ResourceManager.GetString("Grid_ContractID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Khách Hàng.
        /// </summary>
        internal static string Grid_CustomerName {
            get {
                return ResourceManager.GetString("Grid_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Ngày Quá Hạn.
        /// </summary>
        internal static string Grid_DaysOverdue {
            get {
                return ResourceManager.GetString("Grid_DaysOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Ngày Còn Lại.
        /// </summary>
        internal static string Grid_DaysRemaining {
            get {
                return ResourceManager.GetString("Grid_DaysRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ Trách.
        /// </summary>
        internal static string Grid_Department {
            get {
                return ResourceManager.GetString("Grid_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Tiết.
        /// </summary>
        internal static string Grid_Detail {
            get {
                return ResourceManager.GetString("Grid_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Trả Kết Quả.
        /// </summary>
        internal static string Grid_DueDate {
            get {
                return ResourceManager.GetString("Grid_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Viên Thụ Lý.
        /// </summary>
        internal static string Grid_Employee {
            get {
                return ResourceManager.GetString("Grid_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối Đa.
        /// </summary>
        internal static string Grid_Max {
            get {
                return ResourceManager.GetString("Grid_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối Thiểu.
        /// </summary>
        internal static string Grid_Min {
            get {
                return ResourceManager.GetString("Grid_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Duyệt.
        /// </summary>
        internal static string Grid_NotApproved {
            get {
                return ResourceManager.GetString("Grid_NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Ô Nhiễm.
        /// </summary>
        internal static string Grid_NotPolluted {
            get {
                return ResourceManager.GetString("Grid_NotPolluted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Thông Số.
        /// </summary>
        internal static string Grid_ParamName {
            get {
                return ResourceManager.GetString("Grid_ParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ô Nhiễm.
        /// </summary>
        internal static string Grid_Polluted {
            get {
                return ResourceManager.GetString("Grid_Polluted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết Quả.
        /// </summary>
        internal static string Grid_Result {
            get {
                return ResourceManager.GetString("Grid_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu.
        /// </summary>
        internal static string Grid_Sample {
            get {
                return ResourceManager.GetString("Grid_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string Grid_Select {
            get {
                return ResourceManager.GetString("Grid_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ký.
        /// </summary>
        internal static string Grid_SignDate {
            get {
                return ResourceManager.GetString("Grid_SignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp Ô Nhiễm.
        /// </summary>
        internal static string Grid_SoonPolluted {
            get {
                return ResourceManager.GetString("Grid_SoonPolluted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng Thái.
        /// </summary>
        internal static string Grid_Status {
            get {
                return ResourceManager.GetString("Grid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Vị.
        /// </summary>
        internal static string Grid_Unit {
            get {
                return ResourceManager.GetString("Grid_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá Trị.
        /// </summary>
        internal static string Grid_Value {
            get {
                return ResourceManager.GetString("Grid_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Giá Trị Đo.
        /// </summary>
        internal static string Grid_ValueEntry {
            get {
                return ResourceManager.GetString("Grid_ValueEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên Bản.
        /// </summary>
        internal static string Introduce_AppVersion {
            get {
                return ResourceManager.GetString("Introduce_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        internal static string Introduce_Contact {
            get {
                return ResourceManager.GetString("Introduce_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chú Ý.
        /// </summary>
        internal static string Introduce_Notice {
            get {
                return ResourceManager.GetString("Introduce_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần mềm này chứa mã nguồn được cung cấp bởi GREENFLOW Corporation.
        /// </summary>
        internal static string Introduce_Notice_Text {
            get {
                return ResourceManager.GetString("Introduce_Notice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách bảo mật.
        /// </summary>
        internal static string Introduce_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Introduce_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xem lại Chính sách bảo mật để hiểu.
        /// </summary>
        internal static string Introduce_PrivacyPolicy_Text {
            get {
                return ResourceManager.GetString("Introduce_PrivacyPolicy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Thiệu.
        /// </summary>
        internal static string Introduce_Title {
            get {
                return ResourceManager.GetString("Introduce_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng Bộ Phận.
        /// </summary>
        internal static string IsDepartmentHead {
            get {
                return ResourceManager.GetString("IsDepartmentHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu Môi Trường.
        /// </summary>
        internal static string Label_Template {
            get {
                return ResourceManager.GetString("Label_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản.
        /// </summary>
        internal static string Login_Account {
            get {
                return ResourceManager.GetString("Login_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập Bằng Face ID.
        /// </summary>
        internal static string Login_FaceID {
            get {
                return ResourceManager.GetString("Login_FaceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên Mật Khẩu.
        /// </summary>
        internal static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập.
        /// </summary>
        internal static string Login_LoginButton {
            get {
                return ResourceManager.GetString("Login_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Đăng Nhập (Email).
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn đăng xuất?.
        /// </summary>
        internal static string Logout_Confirm_Message {
            get {
                return ResourceManager.GetString("Logout_Confirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác Nhận Đăng xuất.
        /// </summary>
        internal static string Logout_Confirm_Title {
            get {
                return ResourceManager.GetString("Logout_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Kính gửi quý khách hàng,&lt;/p&gt;&lt;p&gt;Công ty Green Flow xin gửi bạn báo cáo kết quả quan trắc môi trường cho hợp đồng &lt;b&gt;{0}&lt;/b&gt; (ID: {1}).&lt;/p&gt;&lt;p&gt;Vui lòng xem chi tiết trong file PDF đính kèm.&lt;/p&gt;
        ///
        ///
        ///&lt;p&gt;Trân trọng,
        ///
        ///
        ///Đội ngũ Green Flow&lt;/p&gt;.
        /// </summary>
        internal static string Mail_Body {
            get {
                return ResourceManager.GetString("Mail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BÁO CÁO KẾT QUẢ] Hợp đồng {0} - Green Flow.
        /// </summary>
        internal static string Mail_Subject {
            get {
                return ResourceManager.GetString("Mail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        internal static string Menu_AI {
            get {
                return ResourceManager.GetString("Menu_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Đồng.
        /// </summary>
        internal static string Menu_Contracts {
            get {
                return ResourceManager.GetString("Menu_Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Thiệu.
        /// </summary>
        internal static string Menu_Introduce {
            get {
                return ResourceManager.GetString("Menu_Introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Báo.
        /// </summary>
        internal static string Menu_Notification {
            get {
                return ResourceManager.GetString("Menu_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài Đặt.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống Kê.
        /// </summary>
        internal static string Menu_Stats {
            get {
                return ResourceManager.GetString("Menu_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Viên.
        /// </summary>
        internal static string Menu_User {
            get {
                return ResourceManager.GetString("Menu_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Đồng Quá Hạn.
        /// </summary>
        internal static string Notification_Panel_Overdue {
            get {
                return ResourceManager.GetString("Notification_Panel_Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Đồng Sắp Quá Hạn.
        /// </summary>
        internal static string Notification_Panel_Soon {
            get {
                return ResourceManager.GetString("Notification_Panel_Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Báo.
        /// </summary>
        internal static string Notification_Title {
            get {
                return ResourceManager.GetString("Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string Pagination_Page {
            get {
                return ResourceManager.GetString("Pagination_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string PDF_Address {
            get {
                return ResourceManager.GetString("PDF_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh Nghiệp.
        /// </summary>
        internal static string PDF_Company {
            get {
                return ResourceManager.GetString("PDF_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký Hiệu Doanh Nghiệp.
        /// </summary>
        internal static string PDF_CompanySymbol {
            get {
                return ResourceManager.GetString("PDF_CompanySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày {0} tháng {1} năm {2}.
        /// </summary>
        internal static string PDF_DateFormat {
            get {
                return ResourceManager.GetString("PDF_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày trả kết quả.
        /// </summary>
        internal static string PDF_DateReturn {
            get {
                return ResourceManager.GetString("PDF_DateReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại diện bên A.
        /// </summary>
        internal static string PDF_Representative {
            get {
                return ResourceManager.GetString("PDF_Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐẠI DIỆN DOANH NGHIỆP.
        /// </summary>
        internal static string PDF_Sign_Company {
            get {
                return ResourceManager.GetString("PDF_Sign_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐẠI DIỆN PHỤ TRÁCH.
        /// </summary>
        internal static string PDF_Sign_Manager {
            get {
                return ResourceManager.GetString("PDF_Sign_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả quan trắc.
        /// </summary>
        internal static string PDF_TableTitle {
            get {
                return ResourceManager.GetString("PDF_TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHIẾU KẾT QUẢ THỬ NGHIỆM.
        /// </summary>
        internal static string PDF_Title {
            get {
                return ResourceManager.GetString("PDF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN CHUNG.
        /// </summary>
        internal static string PDF_TITLEI {
            get {
                return ResourceManager.GetString("PDF_TITLEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện Thoại.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Địa Chỉ.
        /// </summary>
        internal static string Placeholder_Address {
            get {
                return ResourceManager.GetString("Placeholder_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Năm Sinh.
        /// </summary>
        internal static string Placeholder_BirthYear {
            get {
                return ResourceManager.GetString("Placeholder_BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Phòng Ban.
        /// </summary>
        internal static string Placeholder_Department {
            get {
                return ResourceManager.GetString("Placeholder_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Email.
        /// </summary>
        internal static string Placeholder_Email {
            get {
                return ResourceManager.GetString("Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Mã NV.
        /// </summary>
        internal static string Placeholder_EmployeeCode {
            get {
                return ResourceManager.GetString("Placeholder_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Họ Và Tên.
        /// </summary>
        internal static string Placeholder_FullName {
            get {
                return ResourceManager.GetString("Placeholder_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Mật Khẩu.
        /// </summary>
        internal static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Số Điện Thoại.
        /// </summary>
        internal static string Placeholder_Phone {
            get {
                return ResourceManager.GetString("Placeholder_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Thông Số Mới.
        /// </summary>
        internal static string Plan_AddParamButton {
            get {
                return ResourceManager.GetString("Plan_AddParamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm thông số mới vào hệ thống..
        /// </summary>
        internal static string Plan_AddParamSuccess {
            get {
                return ResourceManager.GetString("Plan_AddParamSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Không tìm thấy Mã hợp đồng (MaDon) tương ứng..
        /// </summary>
        internal static string Plan_ContractCodeNotFound {
            get {
                return ResourceManager.GetString("Plan_ContractCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách Hàng.
        /// </summary>
        internal static string Plan_ContractIDLabel {
            get {
                return ResourceManager.GetString("Plan_ContractIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Hợp Đồng.
        /// </summary>
        internal static string Plan_ContractListButton {
            get {
                return ResourceManager.GetString("Plan_ContractListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Mẫu này đã được thêm vào hợp đồng này rồi..
        /// </summary>
        internal static string Plan_DuplicateSampleError {
            get {
                return ResourceManager.GetString("Plan_DuplicateSampleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông số này đã tồn tại trong hệ thống..
        /// </summary>
        internal static string Plan_ParamAlreadyExists {
            get {
                return ResourceManager.GetString("Plan_ParamAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Số.
        /// </summary>
        internal static string Plan_ParametersLabel {
            get {
                return ResourceManager.GetString("Plan_ParametersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu Môi Trường.
        /// </summary>
        internal static string Plan_SampleTemplatesLabel {
            get {
                return ResourceManager.GetString("Plan_SampleTemplatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu kế hoạch cho hợp đồng &apos;{0}&apos; và bàn giao cho Phòng Hiện Trường..
        /// </summary>
        internal static string Plan_SaveSuccess {
            get {
                return ResourceManager.GetString("Plan_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một hợp đồng từ &apos;Danh sách hợp đồng&apos;..
        /// </summary>
        internal static string Plan_SelectContract {
            get {
                return ResourceManager.GetString("Plan_SelectContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ít nhất một thông số đo..
        /// </summary>
        internal static string Plan_SelectParameter {
            get {
                return ResourceManager.GetString("Plan_SelectParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ít nhất một mẫu môi trường..
        /// </summary>
        internal static string Plan_SelectSampleTemplate {
            get {
                return ResourceManager.GetString("Plan_SelectSampleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Hợp đồng.
        /// </summary>
        internal static string Popup_SelectContractTitle {
            get {
                return ResourceManager.GetString("Popup_SelectContractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu để lưu..
        /// </summary>
        internal static string Real_NoDataToSave {
            get {
                return ResourceManager.GetString("Real_NoDataToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu giá trị thành công và bàn giao cho Phòng Thí Nghiệm..
        /// </summary>
        internal static string Real_SaveSuccess {
            get {
                return ResourceManager.GetString("Real_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện Trường.
        /// </summary>
        internal static string Request_FieldDept {
            get {
                return ResourceManager.GetString("Request_FieldDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí nghiệm.
        /// </summary>
        internal static string Request_LabDept {
            get {
                return ResourceManager.GetString("Request_LabDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một phòng ban để chuyển về..
        /// </summary>
        internal static string Request_SelectDeptWarning {
            get {
                return ResourceManager.GetString("Request_SelectDeptWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn phòng ban cần chỉnh sửa.
        /// </summary>
        internal static string Request_Title {
            get {
                return ResourceManager.GetString("Request_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        internal static string Result_Approve {
            get {
                return ResourceManager.GetString("Result_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi duyệt hợp đồng.
        /// </summary>
        internal static string Result_ApproveError {
            get {
                return ResourceManager.GetString("Result_ApproveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã duyệt hợp đồng.
        /// </summary>
        internal static string Result_ApproveSuccess {
            get {
                return ResourceManager.GetString("Result_ApproveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng này không có email. Vui lòng cập nhật..
        /// </summary>
        internal static string Result_EmailNotFound {
            get {
                return ResourceManager.GetString("Result_EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chuẩn bị file PDF để gửi....
        /// </summary>
        internal static string Result_GeneratingPDF {
            get {
                return ResourceManager.GetString("Result_GeneratingPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải kết quả.
        /// </summary>
        internal static string Result_LoadError {
            get {
                return ResourceManager.GetString("Result_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Result_Mail {
            get {
                return ResourceManager.GetString("Result_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi email và file PDF thành công!.
        /// </summary>
        internal static string Result_MailSendSuccess {
            get {
                return ResourceManager.GetString("Result_MailSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string Result_PDF {
            get {
                return ResourceManager.GetString("Result_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Yêu Cầu Chỉnh Sửa.
        /// </summary>
        internal static string Result_RequestEdit {
            get {
                return ResourceManager.GetString("Result_RequestEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi gửi yêu cầu.
        /// </summary>
        internal static string Result_RequestError {
            get {
                return ResourceManager.GetString("Result_RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi yêu cầu chỉnh sửa và chuyển hợp đồng về cho phòng {0}..
        /// </summary>
        internal static string Result_RequestSuccess {
            get {
                return ResourceManager.GetString("Result_RequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nơi lưu hợp đồng.
        /// </summary>
        internal static string Result_SavePDFTitle {
            get {
                return ResourceManager.GetString("Result_SavePDFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn hợp đồng..
        /// </summary>
        internal static string Result_SelectContract {
            get {
                return ResourceManager.GetString("Result_SelectContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn hợp đồng trước khi duyệt..
        /// </summary>
        internal static string Result_SelectContractBeforeApprove {
            get {
                return ResourceManager.GetString("Result_SelectContractBeforeApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn hợp đồng trước khi gửi mail..
        /// </summary>
        internal static string Result_SelectContractBeforeMail {
            get {
                return ResourceManager.GetString("Result_SelectContractBeforeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn hợp đồng trước khi xuất PDF..
        /// </summary>
        internal static string Result_SelectContractBeforePDF {
            get {
                return ResourceManager.GetString("Result_SelectContractBeforePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi báo cáo đến {0}....
        /// </summary>
        internal static string Result_SendingMailTo {
            get {
                return ResourceManager.GetString("Result_SendingMailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai trò.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị viên.
        /// </summary>
        internal static string Role_Admin {
            get {
                return ResourceManager.GetString("Role_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh doanh.
        /// </summary>
        internal static string Role_Business {
            get {
                return ResourceManager.GetString("Role_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện trường.
        /// </summary>
        internal static string Role_Field {
            get {
                return ResourceManager.GetString("Role_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng thí nghiệm.
        /// </summary>
        internal static string Role_Lab {
            get {
                return ResourceManager.GetString("Role_Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch.
        /// </summary>
        internal static string Role_Plan {
            get {
                return ResourceManager.GetString("Role_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả.
        /// </summary>
        internal static string Role_Result {
            get {
                return ResourceManager.GetString("Role_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng Dụng.
        /// </summary>
        internal static string Settings_App {
            get {
                return ResourceManager.GetString("Settings_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face ID.
        /// </summary>
        internal static string Settings_FaceID {
            get {
                return ResourceManager.GetString("Settings_FaceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Kí Face ID.
        /// </summary>
        internal static string Settings_FaceID_Button {
            get {
                return ResourceManager.GetString("Settings_FaceID_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn Ngữ.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Báo.
        /// </summary>
        internal static string Settings_Notification {
            get {
                return ResourceManager.GetString("Settings_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu Hỏi Thường Gặp.
        /// </summary>
        internal static string Settings_Question {
            get {
                return ResourceManager.GetString("Settings_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu Cài Đặt.
        /// </summary>
        internal static string Settings_SaveButton {
            get {
                return ResourceManager.GetString("Settings_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài Đặt Hệ Thống.
        /// </summary>
        internal static string Settings_SystemSettings {
            get {
                return ResourceManager.GetString("Settings_SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ Đề Giao Diện.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ Và Cài Đặt .
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng Dẫn Sử Dụng.
        /// </summary>
        internal static string Settings_UserManual {
            get {
                return ResourceManager.GetString("Settings_UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ Người Dùng.
        /// </summary>
        internal static string Settings_UserSupport {
            get {
                return ResourceManager.GetString("Settings_UserSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Tài Liệu.
        /// </summary>
        internal static string Settings_ViewDocument {
            get {
                return ResourceManager.GetString("Settings_ViewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áp Dụng.
        /// </summary>
        internal static string Stats_ApplyButton {
            get {
                return ResourceManager.GetString("Stats_ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trễ Hẹn.
        /// </summary>
        internal static string Stats_Late {
            get {
                return ResourceManager.GetString("Stats_Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang Tải....
        /// </summary>
        internal static string Stats_Loading {
            get {
                return ResourceManager.GetString("Stats_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng {0}.
        /// </summary>
        internal static string Stats_Month {
            get {
                return ResourceManager.GetString("Stats_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đúng Hẹn.
        /// </summary>
        internal static string Stats_OnTime {
            get {
                return ResourceManager.GetString("Stats_OnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ Lệ Đúng/Trễ Hẹn.
        /// </summary>
        internal static string Stats_OnTimeRate {
            get {
                return ResourceManager.GetString("Stats_OnTimeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Lượng Đơn Hàng.
        /// </summary>
        internal static string Stats_OrderCount {
            get {
                return ResourceManager.GetString("Stats_OrderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý 1.
        /// </summary>
        internal static string Stats_Quarter1 {
            get {
                return ResourceManager.GetString("Stats_Quarter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý 2.
        /// </summary>
        internal static string Stats_Quarter2 {
            get {
                return ResourceManager.GetString("Stats_Quarter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý 3.
        /// </summary>
        internal static string Stats_Quarter3 {
            get {
                return ResourceManager.GetString("Stats_Quarter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý 4.
        /// </summary>
        internal static string Stats_Quarter4 {
            get {
                return ResourceManager.GetString("Stats_Quarter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ Lệ.
        /// </summary>
        internal static string Stats_Rate {
            get {
                return ResourceManager.GetString("Stats_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo Cáo Và Thống Kê.
        /// </summary>
        internal static string Stats_Title {
            get {
                return ResourceManager.GetString("Stats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai định dạng.
        /// </summary>
        internal static string Status_InvalidFormat {
            get {
                return ResourceManager.GetString("Status_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có.
        /// </summary>
        internal static string Status_NotAvailable {
            get {
                return ResourceManager.GetString("Status_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoài giới hạn.
        /// </summary>
        internal static string Status_OutOfRange {
            get {
                return ResourceManager.GetString("Status_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đạt.
        /// </summary>
        internal static string Status_Passed {
            get {
                return ResourceManager.GetString("Status_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo hợp đồng thành công..
        /// </summary>
        internal static string Success_ContractCreated {
            get {
                return ResourceManager.GetString("Success_ContractCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môi trường không khí.
        /// </summary>
        internal static string Template_Air {
            get {
                return ResourceManager.GetString("Template_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng ồn và độ rung.
        /// </summary>
        internal static string Template_Noise {
            get {
                return ResourceManager.GetString("Template_Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môi trường đất.
        /// </summary>
        internal static string Template_Soil {
            get {
                return ResourceManager.GetString("Template_Soil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môi trường nước.
        /// </summary>
        internal static string Template_Water {
            get {
                return ResourceManager.GetString("Template_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối.
        /// </summary>
        internal static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sáng.
        /// </summary>
        internal static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Viên đang phụ trách Hợp đồng &apos;{0}&apos;.
        /// </summary>
        internal static string Usage_Contract {
            get {
                return ResourceManager.GetString("Usage_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đang phụ trách mẫu Hiện trường &apos;{0}&apos;.
        /// </summary>
        internal static string Usage_SampleHT {
            get {
                return ResourceManager.GetString("Usage_SampleHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đang phụ trách mẫu Thí nghiệm &apos;{0}&apos;.
        /// </summary>
        internal static string Usage_SamplePTN {
            get {
                return ResourceManager.GetString("Usage_SamplePTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Địa chỉ..
        /// </summary>
        internal static string Validation_AddressRequired {
            get {
                return ResourceManager.GetString("Validation_AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm sinh phải là một con số (ví dụ: 1990)..
        /// </summary>
        internal static string Validation_BirthYearInvalid {
            get {
                return ResourceManager.GetString("Validation_BirthYearInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm sinh không hợp lệ..
        /// </summary>
        internal static string Validation_BirthYearRange {
            get {
                return ResourceManager.GetString("Validation_BirthYearRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Năm sinh..
        /// </summary>
        internal static string Validation_BirthYearRequired {
            get {
                return ResourceManager.GetString("Validation_BirthYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Phòng ban..
        /// </summary>
        internal static string Validation_DepartmentRequired {
            get {
                return ResourceManager.GetString("Validation_DepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email này đã tồn tại. Vui lòng sử dụng email khác..
        /// </summary>
        internal static string Validation_EmailExists {
            get {
                return ResourceManager.GetString("Validation_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng Email không hợp lệ..
        /// </summary>
        internal static string Validation_EmailFormat {
            get {
                return ResourceManager.GetString("Validation_EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Email..
        /// </summary>
        internal static string Validation_EmailRequired {
            get {
                return ResourceManager.GetString("Validation_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên này đã tồn tại..
        /// </summary>
        internal static string Validation_EmployeeCodeExists {
            get {
                return ResourceManager.GetString("Validation_EmployeeCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Mã nhân viên..
        /// </summary>
        internal static string Validation_EmployeeCodeRequired {
            get {
                return ResourceManager.GetString("Validation_EmployeeCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Họ tên..
        /// </summary>
        internal static string Validation_FullNameRequired {
            get {
                return ResourceManager.GetString("Validation_FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 6 ký tự..
        /// </summary>
        internal static string Validation_PasswordLength {
            get {
                return ResourceManager.GetString("Validation_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Mật khẩu..
        /// </summary>
        internal static string Validation_PasswordRequired {
            get {
                return ResourceManager.GetString("Validation_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Số điện thoại..
        /// </summary>
        internal static string Validation_PhoneRequired {
            get {
                return ResourceManager.GetString("Validation_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một Vai trò..
        /// </summary>
        internal static string Validation_RoleRequired {
            get {
                return ResourceManager.GetString("Validation_RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Năm và Quý..
        /// </summary>
        internal static string Validation_SelectYearAndQuarter {
            get {
                return ResourceManager.GetString("Validation_SelectYearAndQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xác thực.
        /// </summary>
        internal static string Validation_Title {
            get {
                return ResourceManager.GetString("Validation_Title", resourceCulture);
            }
        }
    }
}
