//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Environmental_Monitoring {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Environmental_Monitoring.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        internal static string Menu_AI {
            get {
                return ResourceManager.GetString("Menu_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Đồng.
        /// </summary>
        internal static string Menu_Contracts {
            get {
                return ResourceManager.GetString("Menu_Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Thiệu.
        /// </summary>
        internal static string Menu_Introduce {
            get {
                return ResourceManager.GetString("Menu_Introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Báo.
        /// </summary>
        internal static string Menu_Notification {
            get {
                return ResourceManager.GetString("Menu_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài Đặt.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống Kê.
        /// </summary>
        internal static string Menu_Stats {
            get {
                return ResourceManager.GetString("Menu_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Viên.
        /// </summary>
        internal static string Menu_User {
            get {
                return ResourceManager.GetString("Menu_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng Dụng.
        /// </summary>
        internal static string Settings_App {
            get {
                return ResourceManager.GetString("Settings_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Settings_Email {
            get {
                return ResourceManager.GetString("Settings_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn Ngữ.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Báo.
        /// </summary>
        internal static string Settings_Notification {
            get {
                return ResourceManager.GetString("Settings_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu Hỏi Thường Gặp.
        /// </summary>
        internal static string Settings_Question {
            get {
                return ResourceManager.GetString("Settings_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu Cài Đặt.
        /// </summary>
        internal static string Settings_SaveButton {
            get {
                return ResourceManager.GetString("Settings_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài Đặt Hệ Thống.
        /// </summary>
        internal static string Settings_SystemSettings {
            get {
                return ResourceManager.GetString("Settings_SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ Đề Giao Diện.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ Và Cài Đặt .
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng Dẫn Sử Dụng.
        /// </summary>
        internal static string Settings_UserManual {
            get {
                return ResourceManager.GetString("Settings_UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ Người Dùng.
        /// </summary>
        internal static string Settings_UserSupport {
            get {
                return ResourceManager.GetString("Settings_UserSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Tài Liệu.
        /// </summary>
        internal static string Settings_ViewDocument {
            get {
                return ResourceManager.GetString("Settings_ViewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối.
        /// </summary>
        internal static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sáng.
        /// </summary>
        internal static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
    }
}
